language: generic
dist: bionic
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

before_install:
   - wget -c https://github.com/Seeed-Studio/Seeed_Arduino_atUnified/raw/master/seeed-arduino-ci.sh

script:
   - chmod +x seeed-arduino-ci.sh
   - cat $PWD/seeed-arduino-ci.sh
   - bash $PWD/seeed-arduino-ci.sh
     -b "arduino:avr:uno" -b "arduino:avr:mega"
     with_timer1:mega/with_timer3:uno
     PaulStoffregen/TimerOne
     PaulStoffregen/TimerThree

notifications:
  email:
    on_success: change
    on_failure: change
